import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import {Example2} from "@/app/example2/Example2";
import {Example} from "@/app/example/Example";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/*<Example/>*/}
        {/*<Example2/>*/}
        {/*<br/><br/><br/><br/>*/}
        {/*<br/><br/><br/><br/>*/}
        {/*<br/><br/><br/><br/>*/}
        {children}
      </body>
    </html>
  );
}
