
export const TAROT_NAMES_1 = [
    'The Fool',
    'The Magician',
    'The High Priestess',
    'The Empress',
    'The Emperor',
    'The Hierophant',
    'The Lovers',
    'The Chariot',
    'Strength',
    'The Hermit',
    'Wheel of Fortune',
    'Justice',
    'The Hanged Man',
    'Death',
    'Temperance',
    'The Devil',
    'The Tower',
    'The Star',
    'The Moon',
    'The Sun',
    'Judgment',
    'The World',

    'Ace of Wands',
    'Two of Wands',
    'Three of Wands',
    'Four of Wands',
    'Five of Wands',
    'Six of Wands',
    'Seven of Wands',
    'Eight of Wands',
    'Nine of Wands',
    'Ten of Wands',
    'Page of Wands',
    'Knight of Wands',
    'Queen of Wands',
    'King of Wands',

    'Ace of Cups',
    'Two of Cups',
    'Three of Cups',
    'Four of Cups',
    'Five of Cups',
    'Six of Cups',
    'Seven of Cups',
    'Eight of Cups',
    'Nine of Cups',
    'Ten of Cups',
    'Page of Cups',
    'Knight of Cups',
    'Queen of Cups',
    'King of Cups',

    'Ace of Swords',
    'Two of Swords',
    'Three of Swords',
    'Four of Swords',
    'Five of Swords',
    'Six of Swords',
    'Seven of Swords',
    'Eight of Swords',
    'Nine of Swords',
    'Ten of Swords',
    'Page of Swords',
    'Knight of Swords',
    'Queen of Swords',
    'King of Swords',

    'Ace of Pentacles',
    'Two of Pentacles',
    'Three of Pentacles',
    'Four of Pentacles',
    'Five of Pentacles',
    'Six of Pentacles',
    'Seven of Pentacles',
    'Eight of Pentacles',
    'Nine of Pentacles',
    'Ten of Pentacles',
    'Page of Pentacles',
    'Knight of Pentacles',
    'Queen of Pentacles',
    'King of Pentacles',

];

export const TAROT_SHORT_DESC = [
    'Beginnings',
    'Turning visions into reality',
    'Intuition',
    'Fertility',
    'Strategic planning',
    'Traditions',
    'Partnership',
    'Goal',
    'Strength',
    'Introspection',
    'Wheel',
    'Cause and effect',
    'One option to wait',
    'Rebirth',
    'Balance',
    'Addiction',
    'Ruin',
    'Hope',
    'Unseen problems',
    'Success',
    'Exam',
    'Completion',

    'Inspiration',
    'Planning',
    'Expansion',
    'Homecoming',
    'Competition',
    'Victory',
    'Self-defence',
    'Speed',
    'Persistence',
    'Stress',
    'New project',
    'Creativity',
    'Confidence',
    'Power',

    'New relationship',
    'Romance',
    'Friendship',
    'Apathy',
    'Abandonment',
    'Nostalgia',
    'Self-delusion',
    'Retreat',
    'Jubilance',
    'Fulfillment',
    'New love',
    'Princess Charming',
    'Support',
    'Empathy',

    'New ideas',
    'Decision',
    'Heartbreak',
    'Contemplation',
    'Mental battle win',
    'Paradigm shifting',
    'Mental cheating',
    'No ideas',
    'Run out of ideas',
    'Mental loss',
    'Curious kid',
    'Fast-talking person',
    'A self sufficient person',
    'Strategic thought',

    'new job, raise, promotion, investment, new income',
    'Two choices',
    'Teamwork',
    'Greed',
    'Loss',
    'Generosity',
    'Patience',
    'Mastering',
    'Luxury',
    'Legacy',
    'A patient kid',
    'Reliable person',
    'A resourceful person',
    'Practical leader'
];