const CARD_PATH = 'img/annak/';

export const CARD_WIDTH = 230;
export const CARD_HEIGHT = 350;

enum ECard2 {
    FOOL = `${CARD_PATH}00_fool.jpg`,
    MAGICIAN = `${CARD_PATH}01_magician.jpg`,
    HIGHPRIESTESS = `${CARD_PATH}02_highpriestess.jpg`,
    EMPRESS = `${CARD_PATH}03_empress_neu1.jpg`,
    EMPEROR = `${CARD_PATH}04_emperor.jpg`,
    HIGHPRIEST = `${CARD_PATH}05_highpriest.jpg`,
    LOVERS = `${CARD_PATH}06_lovers.jpg`,
    CHARIOT = `${CARD_PATH}07_chariot.jpg`,
    JUSTICE = `${CARD_PATH}08_justice-neu2.jpg`,
    HERMIT = `${CARD_PATH}09_hermit.jpg`,
    FORTUNE = `${CARD_PATH}10_fortune.jpg`,
    STRENGTH = `${CARD_PATH}11_strength_neu.jpg`,
    HANGEDMAN = `${CARD_PATH}12_hangedman_neu.jpg`,
    DEATH = `${CARD_PATH}13_death.jpg`,
    TEMPERANCE = `${CARD_PATH}14_temperance.jpg`,
    DEVIL = `${CARD_PATH}15_devil.jpg`,
    TOWER = `${CARD_PATH}16_tower.jpg`,
    STAR = `${CARD_PATH}17_star_neu3.jpg`,
    MOON = `${CARD_PATH}18_moon.jpg`,
    SUN = `${CARD_PATH}19_sun_neu.jpg`,
    JUDGEMENT = `${CARD_PATH}20_judgement.jpg`,
    WORLD = `${CARD_PATH}21_world.jpg`,
    CUPS01 = `${CARD_PATH}cups01.jpg`,
    CUPS02 = `${CARD_PATH}cups02.jpg`,
    CUPS03 = `${CARD_PATH}cups03_neu.jpg`,
    CUPS04 = `${CARD_PATH}cups04.jpg`,
    CUPS05 = `${CARD_PATH}cups05.jpg`,
    CUPS06 = `${CARD_PATH}cups06.jpg`,
    CUPS07 = `${CARD_PATH}cups07.jpg`,
    CUPS08 = `${CARD_PATH}cups08.jpg`,
    CUPS09 = `${CARD_PATH}cups09.jpg`,
    CUPS10 = `${CARD_PATH}cups10.jpg`,
    CUPS11 = `${CARD_PATH}cups11.jpg`,
    CUPS12 = `${CARD_PATH}cups12_neu.jpg`,
    CUPS13 = `${CARD_PATH}cups13.jpg`,
    CUPS14 = `${CARD_PATH}cups14.jpg`,
    PENTACLES01 = `${CARD_PATH}pentacles01.jpg`,
    PENTACLES02 = `${CARD_PATH}pentacles02.jpg`,
    PENTACLES03 = `${CARD_PATH}pentacles03.jpg`,
    PENTACLES04 = `${CARD_PATH}pentacles04.jpg`,
    PENTACLES05 = `${CARD_PATH}pentacles05.jpg`,
    PENTACLES06 = `${CARD_PATH}pentacles06.jpg`,
    PENTACLES07 = `${CARD_PATH}pentacles07.jpg`,
    PENTACLES08 = `${CARD_PATH}pentacles08.jpg`,
    PENTACLES09 = `${CARD_PATH}pentacles09.jpg`,
    PENTACLES10 = `${CARD_PATH}pentacles10.jpg`,
    PENTACLES11 = `${CARD_PATH}pentacles11.jpg`,
    PENTACLES12 = `${CARD_PATH}pentacles12.jpg`,
    PENTACLES13 = `${CARD_PATH}pentacles13.jpg`,
    PENTACLES14 = `${CARD_PATH}pentacles14.jpg`,
    RODS01 = `${CARD_PATH}rods01.jpg`,
    RODS02 = `${CARD_PATH}rods02.jpg`,
    RODS03 = `${CARD_PATH}rods03.jpg`,
    RODS04 = `${CARD_PATH}rods04.jpg`,
    RODS05 = `${CARD_PATH}rods05.jpg`,
    RODS06 = `${CARD_PATH}rods06.jpg`,
    RODS07 = `${CARD_PATH}rods07.jpg`,
    RODS08 = `${CARD_PATH}rods08.jpg`,
    RODS09 = `${CARD_PATH}rods09.jpg`,
    RODS10 = `${CARD_PATH}rods10.jpg`,
    RODS11 = `${CARD_PATH}rods11.jpg`,
    RODS12 = `${CARD_PATH}rods12.jpg`,
    RODS13 = `${CARD_PATH}rods13.jpg`,
    RODS14 = `${CARD_PATH}rods14.jpg`,
    SWORDS01 = `${CARD_PATH}swords01.jpg`,
    SWORDS02 = `${CARD_PATH}swords02.jpg`,
    SWORDS03 = `${CARD_PATH}swords03.jpg`,
    SWORDS04 = `${CARD_PATH}swords04.jpg`,
    SWORDS05 = `${CARD_PATH}swords05.jpg`,
    SWORDS06 = `${CARD_PATH}swords06.jpg`,
    SWORDS07 = `${CARD_PATH}swords07.jpg`,
    SWORDS08 = `${CARD_PATH}swords08.jpg`,
    SWORDS09 = `${CARD_PATH}swords09.jpg`,
    SWORDS10 = `${CARD_PATH}swords10.jpg`,
    SWORDS11 = `${CARD_PATH}swords11.jpg`,
    SWORDS12 = `${CARD_PATH}swords12.jpg`,
    SWORDS13 = `${CARD_PATH}swords13.jpg`,
    SWORDS14 = `${CARD_PATH}swords14.jpg`,
    BACK = `img/back2.jpg`, // https://clipart-library.com/free/playing-card-back-png.html
}


export const CARD_BACK = `img/back2.jpg`; // https://clipart-library.com/free/playing-card-back-png.html

export const enum CARD_INDEX {
    FOOL,
    MAGICIAN,
    HIGHPRIESTESS,
    EMPRESS,
    EMPEROR,
    HIGHPRIEST,
    LOVERS,
    CHARIOT,
    JUSTICE,
    HERMIT,
    FORTUNE,
    STRENGTH,
    HANGEDMAN,
    DEATH,
    TEMPERANCE,
    DEVIL,
    TOWER,
    STAR,
    MOON,
    SUN,
    JUDGEMENT,
    WORLD,
    CUPS01,
    CUPS02,
    CUPS03,
    CUPS04,
    CUPS05,
    CUPS06,
    CUPS07,
    CUPS08,
    CUPS09,
    CUPS10,
    CUPS11,
    CUPS12,
    CUPS13,
    CUPS14,
    PENTACLES01,
    PENTACLES02,
    PENTACLES03,
    PENTACLES04,
    PENTACLES05,
    PENTACLES06,
    PENTACLES07,
    PENTACLES08,
    PENTACLES09,
    PENTACLES10,
    PENTACLES11,
    PENTACLES12,
    PENTACLES13,
    PENTACLES14,
    RODS01,
    RODS02,
    RODS03,
    RODS04,
    RODS05,
    RODS06,
    RODS07,
    RODS08,
    RODS09,
    RODS10,
    RODS11,
    RODS12,
    RODS13,
    RODS14,
    SWORDS01,
    SWORDS02,
    SWORDS03,
    SWORDS04,
    SWORDS05,
    SWORDS06,
    SWORDS07,
    SWORDS08,
    SWORDS09,
    SWORDS10,
    SWORDS11,
    SWORDS12,
    SWORDS13,
    SWORDS14
}

export const CARD_IMG_ARR = [
    `${CARD_PATH}00_fool.jpg`,
    `${CARD_PATH}01_magician.jpg`,
    `${CARD_PATH}02_highpriestess.jpg`,
    `${CARD_PATH}03_empress_neu1.jpg`,
    `${CARD_PATH}04_emperor.jpg`,
    `${CARD_PATH}05_highpriest.jpg`,
    `${CARD_PATH}06_lovers.jpg`,
    `${CARD_PATH}07_chariot.jpg`,
    `${CARD_PATH}08_justice-neu2.jpg`,
    `${CARD_PATH}09_hermit.jpg`,
    `${CARD_PATH}10_fortune.jpg`,
    `${CARD_PATH}11_strength_neu.jpg`,
    `${CARD_PATH}12_hangedman_neu.jpg`,
    `${CARD_PATH}13_death.jpg`,
    `${CARD_PATH}14_temperance.jpg`,
    `${CARD_PATH}15_devil.jpg`,
    `${CARD_PATH}16_tower.jpg`,
    `${CARD_PATH}17_star_neu3.jpg`,
    `${CARD_PATH}18_moon.jpg`,
    `${CARD_PATH}19_sun_neu.jpg`,
    `${CARD_PATH}20_judgement.jpg`,
    `${CARD_PATH}21_world.jpg`,
    `${CARD_PATH}cups01.jpg`,
    `${CARD_PATH}cups02.jpg`,
    `${CARD_PATH}cups03_neu.jpg`,
    `${CARD_PATH}cups04.jpg`,
    `${CARD_PATH}cups05.jpg`,
    `${CARD_PATH}cups06.jpg`,
    `${CARD_PATH}cups07.jpg`,
    `${CARD_PATH}cups08.jpg`,
    `${CARD_PATH}cups09.jpg`,
    `${CARD_PATH}cups10.jpg`,
    `${CARD_PATH}cups11.jpg`,
    `${CARD_PATH}cups12_neu.jpg`,
    `${CARD_PATH}cups13.jpg`,
    `${CARD_PATH}cups14.jpg`,
    `${CARD_PATH}pentacles01.jpg`,
    `${CARD_PATH}pentacles02.jpg`,
    `${CARD_PATH}pentacles03.jpg`,
    `${CARD_PATH}pentacles04.jpg`,
    `${CARD_PATH}pentacles05.jpg`,
    `${CARD_PATH}pentacles06.jpg`,
    `${CARD_PATH}pentacles07.jpg`,
    `${CARD_PATH}pentacles08.jpg`,
    `${CARD_PATH}pentacles09.jpg`,
    `${CARD_PATH}pentacles10.jpg`,
    `${CARD_PATH}pentacles11.jpg`,
    `${CARD_PATH}pentacles12.jpg`,
    `${CARD_PATH}pentacles13.jpg`,
    `${CARD_PATH}pentacles14.jpg`,
    `${CARD_PATH}rods01.jpg`,
    `${CARD_PATH}rods02.jpg`,
    `${CARD_PATH}rods03.jpg`,
    `${CARD_PATH}rods04.jpg`,
    `${CARD_PATH}rods05.jpg`,
    `${CARD_PATH}rods06.jpg`,
    `${CARD_PATH}rods07.jpg`,
    `${CARD_PATH}rods08.jpg`,
    `${CARD_PATH}rods09.jpg`,
    `${CARD_PATH}rods10.jpg`,
    `${CARD_PATH}rods11.jpg`,
    `${CARD_PATH}rods12.jpg`,
    `${CARD_PATH}rods13.jpg`,
    `${CARD_PATH}rods14.jpg`,
    `${CARD_PATH}swords01.jpg`,
    `${CARD_PATH}swords02.jpg`,
    `${CARD_PATH}swords03.jpg`,
    `${CARD_PATH}swords04.jpg`,
    `${CARD_PATH}swords05.jpg`,
    `${CARD_PATH}swords06.jpg`,
    `${CARD_PATH}swords07.jpg`,
    `${CARD_PATH}swords08.jpg`,
    `${CARD_PATH}swords09.jpg`,
    `${CARD_PATH}swords10.jpg`,
    `${CARD_PATH}swords11.jpg`,
    `${CARD_PATH}swords12.jpg`,
    `${CARD_PATH}swords13.jpg`,
    `${CARD_PATH}swords14.jpg`
];

export const DECK = [
    CARD_INDEX.FOOL,
    CARD_INDEX.MAGICIAN,
    CARD_INDEX.HIGHPRIESTESS,
    CARD_INDEX.EMPRESS,
    CARD_INDEX.EMPEROR,
    CARD_INDEX.HIGHPRIEST,
    CARD_INDEX.LOVERS,
    CARD_INDEX.CHARIOT,
    CARD_INDEX.JUSTICE,
    CARD_INDEX.HERMIT,
    CARD_INDEX.FORTUNE,
    CARD_INDEX.STRENGTH,
    CARD_INDEX.HANGEDMAN,
    CARD_INDEX.DEATH,
    CARD_INDEX.TEMPERANCE,
    CARD_INDEX.DEVIL,
    CARD_INDEX.TOWER,
    CARD_INDEX.STAR,
    CARD_INDEX.MOON,
    CARD_INDEX.SUN,
    CARD_INDEX.JUDGEMENT,
    CARD_INDEX.WORLD,
    CARD_INDEX.CUPS01,
    CARD_INDEX.CUPS02,
    CARD_INDEX.CUPS03,
    CARD_INDEX.CUPS04,
    CARD_INDEX.CUPS05,
    CARD_INDEX.CUPS06,
    CARD_INDEX.CUPS07,
    CARD_INDEX.CUPS08,
    CARD_INDEX.CUPS09,
    CARD_INDEX.CUPS10,
    CARD_INDEX.CUPS11,
    CARD_INDEX.CUPS12,
    CARD_INDEX.CUPS13,
    CARD_INDEX.CUPS14,
    CARD_INDEX.PENTACLES01,
    CARD_INDEX.PENTACLES02,
    CARD_INDEX.PENTACLES03,
    CARD_INDEX.PENTACLES04,
    CARD_INDEX.PENTACLES05,
    CARD_INDEX.PENTACLES06,
    CARD_INDEX.PENTACLES07,
    CARD_INDEX.PENTACLES08,
    CARD_INDEX.PENTACLES09,
    CARD_INDEX.PENTACLES10,
    CARD_INDEX.PENTACLES11,
    CARD_INDEX.PENTACLES12,
    CARD_INDEX.PENTACLES13,
    CARD_INDEX.PENTACLES14,
    CARD_INDEX.RODS01,
    CARD_INDEX.RODS02,
    CARD_INDEX.RODS03,
    CARD_INDEX.RODS04,
    CARD_INDEX.RODS05,
    CARD_INDEX.RODS06,
    CARD_INDEX.RODS07,
    CARD_INDEX.RODS08,
    CARD_INDEX.RODS09,
    CARD_INDEX.RODS10,
    CARD_INDEX.RODS11,
    CARD_INDEX.RODS12,
    CARD_INDEX.RODS13,
    CARD_INDEX.RODS14,
    CARD_INDEX.SWORDS01,
    CARD_INDEX.SWORDS02,
    CARD_INDEX.SWORDS03,
    CARD_INDEX.SWORDS04,
    CARD_INDEX.SWORDS05,
    CARD_INDEX.SWORDS06,
    CARD_INDEX.SWORDS07,
    CARD_INDEX.SWORDS08,
    CARD_INDEX.SWORDS09,
    CARD_INDEX.SWORDS10,
    CARD_INDEX.SWORDS11,
    CARD_INDEX.SWORDS12,
    CARD_INDEX.SWORDS13,
    CARD_INDEX.SWORDS14
];

export const TAROT_NAMES = [
    'The Fool',
    'The Magician',
    'The High Priestess',
    'The Empress',
    'The Emperor',
    'The Hierophant',
    'The Lovers',
    'The Chariot',
    'Strength',
    'The Hermit',
    'Wheel of Fortune',
    'Justice',
    'The Hanged Man',
    'Death',
    'Temperance',
    'The Devil',
    'The Tower',
    'The Star',
    'The Moon',
    'The Sun',
    'Judgment',
    'The World',
    'Ace of Wands',
    'Two of Wands',
    'Three of Wands',
    'Four of Wands',
    'Five of Wands',
    'Six of Wands',
    'Seven of Wands',
    'Eight of Wands',
    'Nine of Wands',
    'Ten of Wands',
    'Page of Wands',
    'Knight of Wands',
    'Queen of Wands',
    'King of Wands',
    'Ace of Cups',
    'Two of Cups',
    'Three of Cups',
    'Four of Cups',
    'Five of Cups',
    'Six of Cups',
    'Seven of Cups',
    'Eight of Cups',
    'Nine of Cups',
    'Ten of Cups',
    'Page of Cups',
    'Knight of Cups',
    'Queen of Cups',
    'King of Cups',
    'Ace of Swords',
    'Two of Swords',
    'Three of Swords',
    'Four of Swords',
    'Five of Swords',
    'Six of Swords',
    'Seven of Swords',
    'Eight of Swords',
    'Nine of Swords',
    'Ten of Swords',
    'Page of Swords',
    'Knight of Swords',
    'Queen of Swords',
    'King of Swords',
    'Ace of Pentacles',
    'Two of Pentacles',
    'Three of Pentacles',
    'Four of Pentacles',
    'Five of Pentacles',
    'Six of Pentacles',
    'Seven of Pentacles',
    'Eight of Pentacles',
    'Nine of Pentacles',
    'Ten of Pentacles',
    'Page of Pentacles',
    'Knight of Pentacles',
    'Queen of Pentacles',
    'King of Pentacles'
];

export enum EArea {
    ADVENTURE0,
    ADVENTURE1,
    ADVENTURE2,
    ADVENTURE3,
    WISDOM,
    SHIELD,
    SWORD,
    SATCHEL
}

export const AreaNames = [
    "Adventure0",
    "Adventure1",
    "Adventure2",
    "Adventure3",
    "Wisdom",
    "Shield",
    "Sword",
    "Satchel"
]
